# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0021_epgsource_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='epgsource',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
